# 01 - Data Pull

Loads the raw Instagram/Facebook CSVs and the raw USDA CSVs, does basic exploration (shape, columns, head), and saves a combined version of the Instagram data to `cleaned_data/` for the next notebook to pick up.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
# are all dfs from instagram - no. of views is NaN, so can use no. of likes as a substitution variable (limitation: can't control for influencer's following base)
df1 = pd.read_csv('../data/manya_first_12012024.csv')     
df2 = pd.read_csv('../data/manya_0711-1104.csv')   
df3 = pd.read_csv('../data/manya_1105_1201.csv')     
df4 = pd.read_csv('../data/manya_0410-0710.csv') 

#df1 = pd.read_csv(r'C:\Users\minni\Downloads\QSS20\covid_food_trends_project\data\manya_first_12012024.csv')
#df2 = pd.read_csv(r'C:\Users\minni\Downloads\QSS20\covid_food_trends_project\data\manya_0711-1104.csv')
#df3 = pd.read_csv(r'C:\Users\minni\Downloads\QSS20\covid_food_trends_project\data\manya_1105_1201.csv')
#df4 = pd.read_csv(r'C:\Users\minni\Downloads\QSS20\covid_food_trends_project\data\manya_0410-0710.csv')

pd.set_option('display.max_colwidth', None)

## Data exploration/understanding basic attributes

In [20]:
df_full = pd.concat([df1, df2, df3, df4], ignore_index=True)
df_full["date_parsed_check"] = pd.to_datetime(df_full["creation_time"], errors="coerce", utc=True)
print(df_full["date_parsed_check"].dt.to_period("M").value_counts().sort_index())
df_full.shape

date_parsed_check
2019-12    10292
2020-01    12543
2020-02    12888
2020-03    22690
2020-04    51220
2020-05    40468
2020-06    27010
2020-07    26869
2020-08    25741
2020-09    23742
2020-10    23005
2020-11    21453
2020-12      714
Freq: M, Name: count, dtype: int64

C:\Users\minni\AppData\Local\Temp\ipykernel_1480\2188914887.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  print(df_full["date_parsed_check"].dt.to_period("M").value_counts().sort_index())

(298635, 20)

In [6]:
df1.columns
df1.shape

(92876, 19)

In [7]:
df1.head()
# looks like instagram - further filter down to specific key words in the hashtag column and description column
#            Get the dates, and construct a bar graph for frequency of posts per month per trendy food

,content_type,creation_time,hashtags,id,is_branded_content,lang,match_type,mcl_url,modified_time,multimedia,post_owner.id,post_owner.name,post_owner.type,post_owner.username,statistics.comment_count,statistics.like_count,statistics.views,statistics.views_date_last_refreshed,text
0,albums,2020-04-20T23:59:45+00:00,"[""quarantinebaking"",""baking"",""desserts"",""instagood"",""hungryaf"",""foodstagram"",""instayum"",""foodwinewomen"",""foodporn"",""todayfood"",""foodgawker"",""yahoofood"",""foodpornshare"",""eeeeeats"",""buzzfeedfood"",""recipeshare"",""huffposttaste"",""instadesserts"",""dessertporn"",""recipes"",""instafood"",""foodie"",""domesticrebelrecipe"",""buzzfeast"",""f52grams"",""domesticrebel""]",1088417516855597,False,en,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/1088417516855597/,2024-05-05T08:37:14+00:00,"[{""id"":""1612430087154407"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZuN0YQbz3uMKwH7d4011oelMFqoj9ooAq9PEevxTCPgvOyn0UZNjiKvsdkwdT_eVX3ji_qJafgTYe9eaGOgA9LsoADcAz_JveGTL_KaL8b93HQZvmZBPPDmYg9AkaxaHYIRjkogMnChuLsZZhjE""},{""id"":""1050268497615668"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZvN8dfHHhQ8oDf0ISEtCFhWUSrncq6XP1JPLraD849VROrNs-hdt7jsaYA8xJNSEgD0rCgUfl5UcC1j8tg3zDB-ykMOxaFAbspl1b2MsyGNiLZzB3B3vl9o8dY7-KT8impDV_mNpvycIC3FealC""}]",1057960431969531,Hayley Parker,creator,thedomesticrebel,14.0,751.0,NaN,NaN,"If you missed it, I made this BEST EVER BLUEBERRY BANANA BREAD on my Stories! 🍌💙 Definitely check it out because this bread is outta this world AMAZING! ✨ Supremely moist and soft with a tender crumb and studded with juicy blueberries! 🤤 Link in my bio and check the highlights tab for the step-by-step video! .\n.\n.\n.\n.\n.\n.\n.\n.\n\nhttps://thedomesticrebel.com/2020/01/13/best-ever-blueberry-banana-bread/"
1,photos,2020-04-20T23:59:21+00:00,"[""bhfyp"",""dieta"",""sano"",""realfood"",""vidasaludable"",""a"",""healthy"",""nutricion"",""foodporn"",""n"",""alimentacionsaludable"",""comidacasera"",""fitness"",""comidareal"",""comidasaludable"",""chile"",""comidasana"",""saludable"",""food"",""comida"",""instafood"",""healthyfood"",""healthylifestyle"",""salud"",""vidasana"",""foodie"",""fit"",""bajardepeso""]",1771885047575204,False,es,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/1771885047575204/,2026-01-31T18:36:47+00:00,"[{""id"":""1771885047575204"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZv6Ei6WTdANgNUPMREDS9s3x7Qs7uaKxRLoNGia85aoVuqEUx-PXl6KatuutJMF-Yw-Q_dmrNM23uVe2bSm8H3cCOCjRAD8SSUp4NGb9b4yiM6nr74k15nkaFBq9gJbXUY2jjyVJb_dqauFSlHb""}]",4479748745601211,Nta. Stephanie Siebert,creator,elblogdelosaludable,1.0,109.0,NaN,NaN,"𝐃𝐀𝐋𝐆𝐎𝐍𝐀 𝐂𝐎𝐅𝐅𝐄𝐄 ☕️\n.\nAquí les traigo el café más viralizado de la cuarentena😅! También conocido como Fluffy Coffee 👏🏼 fácil de hacer y se siente como estar tomándose un frappuccino 🤤. Los que no lo han hecho aún, denle una oportunidad!\n.\nEl paso a paso lo deje en las historias destacadas “SNACKS”\n➖\n🥣Ingredientes:\n• 2 cucharadas de cafe instantaneo\n• 2 cucharadas de azucar (yo use de coco, puedes usar la que quieras)\n• 2 cucharadas de agua\n➖\n👩🏼‍🍳Procedimiento:\nPon todos los ingredientes en un recipiente y mezcla con una batidora hasta que se forme un tipo de “merengue”! Luego, en un vaso aparte agregas leche (la que quieras) con hielo, le pones este merengue encima y listo! Así de facil 👏🏼\n.\n.\n.\n.\n.\n\n#comidasana #comidasaludable #saludable #healthyfood #comida #food #fitness #salud #comidareal #vidasana #nutricion #instafood #realfood #n #a #healthy #fit #comidacasera #foodporn #dieta #vidasaludable #sano #healthylifestyle #bajardepeso #chile #alimentacionsaludable #foodie #bhfyp"
2,albums,2020-04-20T23:58:46+00:00,"[""quarantinecooking"",""coronaviruspandemic"",""severalpeoplesmama"",""quarantinelifebelike"",""itsbetterwhenitsseasoned"",""drinkrecipes"",""mimosasunrise"",""busymomlife"",""eatinggoodfood"",""strawberrysyrup"",""budgetcommunity"",""houstonfoodblog"",""strawberrylemonade\ud83c\udf53\ud83c\udf4b"",""singlemamalife"",""frugalmom"",""cookingdiaries\ud83c\udf74"",""smartmama"",""onabudget"",""eatathome"",""dinnerinspiration"",""sweetdrinks"",""cookyomeals"",""busymamas"",""easymealideas"",""budgetshopper"",""frugalshopper""]",1799792738102118,False,en,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/1799792738102118/,2026-05-02T13:54:35+00:00,NaN,527415093458990,Rickey Nicole,creator,severalpeoplesmama,12.0,122.0,NaN,NaN,Swipe ⬅️ Homemade Strawberry 🍓 Syrup & 2 Drink recipes you can enjoy with it are now on the blog! Link in bio😉 •\n•\n•\n•\n•\n•\n•\n•\n•\n•\n\n#coronaviruspandemic #sweetdrinks #quarantinelifebelike #quarantinecooking #eatathome #smartmama #singlemamalife #busymamas #easymealideas #dinnerinspiration #strawberrysyrup #mimosasunrise #busymomlife #onabudget #budgetshopper #frugalmom #frugalshopper #budgetcommunity #drinkrecipes #strawberrylemonade🍓🍋 #houstonfoodblog #eatinggoodfood #severalpeoplesmama #itsbetterwhenitsseasoned #cookyomeals #cookingdiaries🍴
3,photos,2020-04-20T23:57:49+00:00,"[""legumesvietnam"",""bananabread"",""banana"",""diet"",""legumes"",""healthy""]",991267910636745,False,vi,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/991267910636745/,2026-05-08T00:40:38+00:00,"[{""id"":""991267910636745"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZvYSlF50IJirRMT-MNUVHuKR42N4NFhQzmPicjrkMerbsxfY0ouT_BhiJ2QyDD-0xERVc8xH-QeXZFadhUhjQQ1fxsxNn1MV84gw4noECgUSdMrdnFIQrMfI2YNx6puBKo_kJ1AquhGOsaRR2A""}]",540414592331420,The Organic Juice • Légumes ®,business,legumesvietnam,0.0,21.0,NaN,NaN,"Nên ăn sáng như thế nào để vừa ngon, vừa đầy đủ dinh dưỡng, nhưng vẫn không sợ tăng cân ?? 👉🏻👉🏻 Hãy thử ngay với vài lát bánh Chuối từ Légumes nhé. Với công thức hoàn toàn đặc biệt, chỉ có riêng tại Légumes, bạn sẽ hoàn toàn bất ngờ với những lát bánh đầu tiên. ▪️Thành phần được làm từ những nguyên liệu vô cùng có lợi cho sức khỏe như: Bột yến mạch gluten-free, Bột mì, Chuối, Chà Là và Dầu Olive nguyên chất.\n____________________________\n\nHow to eat breakfast to be both delicious and nutritious, but still not afraid to gain weight ?? 👉🏻👉🏻Try some slice of Banana Bread from Légumes. With a completely special recipe, only at Légumes, you will be completely surprised with the first slice of bread. ▪️Ingredients made from extremely healthy ingredients such as gluten-free oatmeal, Flour, Banana, Dates, and Extra Virgin Olive Oil. 🔶🔹🔷🔸🔶🔸🔷🔹 The Organic Juice • Légumes\n📍 : 40 Nguyễn Cừ, Thảo Điền, quận 2\n☎ : 08.8899.1331\n📧 : contact@legumesvn.com\n🌐 : www.legumesvn.com\nInbox: m.me/legumesvietnam 🔶🔸🔷🔹🔶🔸🔷🔹\n#banana #bananabread #healthy #diet\n#legumes #legumesvietnam"
4,photos,2020-04-20T23:55:03+00:00,"[""quarantinecooking"",""foodblogeats"",""easydinnerideas"",""budgetcooking"",""foodfolksandfun"",""enchiladasoup""]",4055778088055353,False,en,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/4055778088055353/,2026-01-28T09:41:58+00:00,"[{""id"":""4055778088055353"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZv22Eo24WoGxXSx4J7MIyb3sWVJ_Ny_4tJRUZcM7kf2iDe5bFjy7URY7rrNjI9fiJ6V774dTFWd-3wlw-7S4wy9BZHEAb6D4H3yasGSR9vUqd_ofI6McEzZmSt6EUU07RDbqBx9RhsFLuWfuJwX""}]",1562772411678292,Jillian Wade | Comfort Food Recipes,creator,foodfolksandfun,18.0,143.0,NaN,NaN,"This quick and easy Chicken Enchilada Soup recipe is cheesy, thick, and loaded with black beans, corn, tomatoes, green chile, and cheese! The best part is that it’s ready in 30 minutes or less! This recipe serves 6 and costs just $1.81 per serving! #foodfolksandfun #foodblogeats #enchiladasoup #easydinnerideas #budgetcooking #quarantinecooking"

In [8]:
df2.head()
df2.shape

(93520, 19)

In [9]:
df3.head()
df3.shape

(19409, 19)

In [10]:
df4.head()
df4.shape

(92830, 19)

In [11]:
print(df_full.columns.tolist())
df_full.head(3)

['content_type', 'creation_time', 'hashtags', 'id', 'is_branded_content', 'lang', 'match_type', 'mcl_url', 'modified_time', 'multimedia', 'post_owner.id', 'post_owner.name', 'post_owner.type', 'post_owner.username', 'statistics.comment_count', 'statistics.like_count', 'statistics.views', 'statistics.views_date_last_refreshed', 'text']

,content_type,creation_time,hashtags,id,is_branded_content,lang,match_type,mcl_url,modified_time,multimedia,post_owner.id,post_owner.name,post_owner.type,post_owner.username,statistics.comment_count,statistics.like_count,statistics.views,statistics.views_date_last_refreshed,text
0,albums,2020-04-20T23:59:45+00:00,"[""quarantinebaking"",""baking"",""desserts"",""instagood"",""hungryaf"",""foodstagram"",""instayum"",""foodwinewomen"",""foodporn"",""todayfood"",""foodgawker"",""yahoofood"",""foodpornshare"",""eeeeeats"",""buzzfeedfood"",""recipeshare"",""huffposttaste"",""instadesserts"",""dessertporn"",""recipes"",""instafood"",""foodie"",""domesticrebelrecipe"",""buzzfeast"",""f52grams"",""domesticrebel""]",1088417516855597,False,en,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/1088417516855597/,2024-05-05T08:37:14+00:00,"[{""id"":""1612430087154407"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZuN0YQbz3uMKwH7d4011oelMFqoj9ooAq9PEevxTCPgvOyn0UZNjiKvsdkwdT_eVX3ji_qJafgTYe9eaGOgA9LsoADcAz_JveGTL_KaL8b93HQZvmZBPPDmYg9AkaxaHYIRjkogMnChuLsZZhjE""},{""id"":""1050268497615668"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZvN8dfHHhQ8oDf0ISEtCFhWUSrncq6XP1JPLraD849VROrNs-hdt7jsaYA8xJNSEgD0rCgUfl5UcC1j8tg3zDB-ykMOxaFAbspl1b2MsyGNiLZzB3B3vl9o8dY7-KT8impDV_mNpvycIC3FealC""}]",1057960431969531,Hayley Parker,creator,thedomesticrebel,14.0,751.0,NaN,NaN,"If you missed it, I made this BEST EVER BLUEBERRY BANANA BREAD on my Stories! 🍌💙 Definitely check it out because this bread is outta this world AMAZING! ✨ Supremely moist and soft with a tender crumb and studded with juicy blueberries! 🤤 Link in my bio and check the highlights tab for the step-by-step video! .\n.\n.\n.\n.\n.\n.\n.\n.\n\nhttps://thedomesticrebel.com/2020/01/13/best-ever-blueberry-banana-bread/"
1,photos,2020-04-20T23:59:21+00:00,"[""bhfyp"",""dieta"",""sano"",""realfood"",""vidasaludable"",""a"",""healthy"",""nutricion"",""foodporn"",""n"",""alimentacionsaludable"",""comidacasera"",""fitness"",""comidareal"",""comidasaludable"",""chile"",""comidasana"",""saludable"",""food"",""comida"",""instafood"",""healthyfood"",""healthylifestyle"",""salud"",""vidasana"",""foodie"",""fit"",""bajardepeso""]",1771885047575204,False,es,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/1771885047575204/,2026-01-31T18:36:47+00:00,"[{""id"":""1771885047575204"",""type"":""photo"",""url"":""https://lookaside.facebook.com/mcl/multimedia/lookaside/?download_info=AZv6Ei6WTdANgNUPMREDS9s3x7Qs7uaKxRLoNGia85aoVuqEUx-PXl6KatuutJMF-Yw-Q_dmrNM23uVe2bSm8H3cCOCjRAD8SSUp4NGb9b4yiM6nr74k15nkaFBq9gJbXUY2jjyVJb_dqauFSlHb""}]",4479748745601211,Nta. Stephanie Siebert,creator,elblogdelosaludable,1.0,109.0,NaN,NaN,"𝐃𝐀𝐋𝐆𝐎𝐍𝐀 𝐂𝐎𝐅𝐅𝐄𝐄 ☕️\n.\nAquí les traigo el café más viralizado de la cuarentena😅! También conocido como Fluffy Coffee 👏🏼 fácil de hacer y se siente como estar tomándose un frappuccino 🤤. Los que no lo han hecho aún, denle una oportunidad!\n.\nEl paso a paso lo deje en las historias destacadas “SNACKS”\n➖\n🥣Ingredientes:\n• 2 cucharadas de cafe instantaneo\n• 2 cucharadas de azucar (yo use de coco, puedes usar la que quieras)\n• 2 cucharadas de agua\n➖\n👩🏼‍🍳Procedimiento:\nPon todos los ingredientes en un recipiente y mezcla con una batidora hasta que se forme un tipo de “merengue”! Luego, en un vaso aparte agregas leche (la que quieras) con hielo, le pones este merengue encima y listo! Así de facil 👏🏼\n.\n.\n.\n.\n.\n\n#comidasana #comidasaludable #saludable #healthyfood #comida #food #fitness #salud #comidareal #vidasana #nutricion #instafood #realfood #n #a #healthy #fit #comidacasera #foodporn #dieta #vidasaludable #sano #healthylifestyle #bajardepeso #chile #alimentacionsaludable #foodie #bhfyp"
2,albums,2020-04-20T23:58:46+00:00,"[""quarantinecooking"",""coronaviruspandemic"",""severalpeoplesmama"",""quarantinelifebelike"",""itsbetterwhenitsseasoned"",""drinkrecipes"",""mimosasunrise"",""busymomlife"",""eatinggoodfood"",""strawberrysyrup"",""budgetcommunity"",""houstonfoodblog"",""strawberrylemonade\ud83c\udf53\ud83c\udf4b"",""singlemamalife"",""frugalmom"",""cookingdiaries\ud83c\udf74"",""smartmama"",""onabudget"",""eatathome"",""dinnerinspiration"",""sweetdrinks"",""cookyomeals"",""busymamas"",""easymealideas"",""budgetshopper"",""frugalshopper""]",1799792738102118,False,en,"[""post_text""]",https://www.facebook.com/transparency-tools/content-library/dataset/1119037145491882/instagram/post/1799792738102118/,2026-05-02T13:54:35+00:00,NaN,527415093458990,Rickey Nicole,creator,severalpeoplesmama,12.0,122.0,NaN,NaN,Swipe ⬅️ Homemade Strawberry 🍓 Syrup & 2 Drink recipes you can enjoy with it are now on the blog! Link in bio😉 •\n•\n•\n•\n•\n•\n•\n•\n•\n•\n\n#coronaviruspandemic #sweetdrinks #quarantinelifebelike #quarantinecooking #eatathome #smartmama #singlemamalife #busymamas #easymealideas #dinnerinspiration #strawberrysyrup #mimosasunrise #busymomlife #onabudget #budgetshopper #frugalmom #frugalshopper #budgetcommunity #drinkrecipes #strawberrylemonade🍓🍋 #houstonfoodblog #eatinggoodfood #severalpeoplesmama #itsbetterwhenitsseasoned #cookyomeals #cookingdiaries🍴

## Importing the raw Food Sales data (USDA)

In [13]:
food_sales1 = pd.read_csv('../data/StateAndCategory.csv') 
food_sales2 = pd.read_csv('../data/NationalTotalAndSubcategory.csv')

In [14]:
food_sales1.head()
#food_sales1.shape
#food_sales2.columns

         Date    State Category Variable       Value
0  2019-10-06  Alabama  Alcohol  Dollars  23611285.0
1  2019-10-13  Alabama  Alcohol  Dollars  23220758.0
2  2019-10-20  Alabama  Alcohol  Dollars  21770283.0
3  2019-10-27  Alabama  Alcohol  Dollars  21956558.0
4  2019-11-03  Alabama  Alcohol  Dollars  23183482.0

In [15]:
food_sales2.head()
#food_sales2['Subcategory'].unique()
#food_sales2.shape
#food_sales2.columns

,Date,Category,Subcategory,Variable,Value
0,2019-10-06,Alcohol,Other,Dollars,1.150829e+09
1,2019-10-06,All foods,All foods,Dollars,1.304327e+10
2,2019-10-06,Beverages,Carbonated non-alcoholic,Dollars,7.350713e+08
3,2019-10-06,Beverages,Fruit drinks and non-carbonated sugary,Dollars,7.290711e+08
4,2019-10-06,Beverages,Other,Dollars,2.271993e+08

## Saving output for next notebook

Saves the combined (but not yet cleaned) Instagram data so `02_data_cleaning.ipynb` can pick up from here without re-running the load/concat steps above.

In [17]:
df_full.to_csv('../cleaned_data/instagram_combined_raw.csv', index=False)
print('Saved instagram_combined_raw.csv with shape:', df_full.shape)

Saved instagram_combined_raw.csv with shape: (298635, 19)

In [21]:
import os
print(os.getcwd())

C:\Users\minni\Downloads\QSS20\covid_food_trends_project\code